### ISSUE TITLE
After the 3rd anniversary update, I can't choose from certain songs to different characters.

### ISSUE THREAD

**Issue by 9oodra** [MarshmallowAndroid/UmaMusumeExplorer#10]
Umapyoi Densetsu
May I ask you to check?
I can't pick a different character.
And the overall volume of the U.M.A World song is jagged unlike in-game.
If possible, please check this too....
Thank you always.

![image](https://github.com/MarshmallowAndroid/UmaMusumeExplorer/assets/88673195/eac3a698-7111-4399-a771-b084e117946e)

**Comment by MarshmallowAndroid** [comment]
Thank you for reporting. I've fixed the issue with Umapyoi Densetsu in the latest commit. However, I'm still be investigating the audio volume issue.

**Comment by 9oodra** [comment]
Thanks!
