### ISSUE TITLE
A small question

### ISSUE THREAD

**Issue by RTMKXXIII** [MarshmallowAndroid/UmaMusumeExplorer#12]
Greeting! Thank you for your prompt updates. [うまぴょい伝説] in Live Music Player is all good now.
By the way,In this new version，how could I open Live Music Player Menu?
![W4 D$9W)W4@~}E`$}6 )D~P](https://github.com/MarshmallowAndroid/UmaMusumeExplorer/assets/127142042/6b9a72e9-1cb9-4c10-8772-83fddea6f9b2)←like this in old version

![MBWSJD AB0TC46WRD)()}LK](https://github.com/MarshmallowAndroid/UmaMusumeExplorer/assets/127142042/9f7f92d6-fe29-42a3-99fc-d43cf39a3b06)←I tried right click in Music player window, but look likes it shows nothing, and Music player window remains the same, Regardless of whether I checked the "Enable SFX" checkbox.
I'm not sure if this is a bug or just me not finding a way. Sorry for bothering you again. Thank you for your great work.
PS:Is it possible to add a loop button to the Music player window?

**Comment by MarshmallowAndroid** [comment]
It would seem as if the window didn't scale properly. I use 100% scale and it's supposed to look like this:
![image](https://github.com/MarshmallowAndroid/UmaMusumeExplorer/assets/19908167/8b6c12bf-46f9-47a7-b000-e0f69df9c4d2)

I'll work on fixing the program for different scales. Thank you for your patience.

**Comment by RTMKXXIII** [comment]
Thank you! My screen resolution is 1920×1080 when using an external monitor with the laptop screen closed. it might be helpful.

**Comment by MarshmallowAndroid** [comment]
The issue with the live music player window size has been fixed. As for the loop function, I'll figure out a way to implement it. Thanks again for reporting!
