### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by yukisetsuna71** [MarshmallowAndroid/UmaMusumeExplorer#13]
There's an error message that says "Error reading tables. Please launch the game and allow itself to repair." I launched the game but the same error message keeps popping up. How do I fix this?

**Comment by MarshmallowAndroid** [comment]
Sorry for the late response. If you're still having this error, I made another build where the message is a little more specific. Please try running it so I may help with the issue.

[win-x64.zip](https://github.com/MarshmallowAndroid/UmaMusumeExplorer/files/15217666/win-x64.zip)

**Comment by yukisetsuna71** [comment]
It says that there is no such table as available_skill_set. I did a full download of the game and re-ran it multiple times so I'm not sure what the issues is.

**Comment by MarshmallowAndroid** [comment]
Are you using the DMM Game Player version?

**Comment by yukisetsuna71** [comment]
Yes.

**Comment by MarshmallowAndroid** [comment]
Please check if the file `C:\Users\<your_username>\AppData\LocalLow\Cygames\umamusume\master\master.mdb` exists and is around ~25 MB.

**Comment by yukisetsuna71** [comment]
It exists but it's zero bytes for some reason.

**Comment by MarshmallowAndroid** [comment]
Try deleting it and running the game again. If it doesn't appear, it means the game is storing it in a different location and the reason it appeared in the first place must be because the library I use creates the file by default when it doesn't exist (which I have since fixed).

**Comment by yukisetsuna71** [comment]
Fixed. Thanks
