### ISSUE TITLE
Two More Questions About the Release v1.2

### ISSUE THREAD

**Issue by ChihyuenWang** [MarshmallowAndroid/UmaMusumeExplorer#3]
Excuse me for disturbing you again.
1. In the new function "Live Music Player", when I click a song, and click "Confirm" in the "Character Select" window, the program doesn't reflect. Only when I close this window manually, the next playback window will pop up. (Switching character has taken effect at this time)
![Snipaste_2022-09-20_08-09-10](https://user-images.githubusercontent.com/12523783/191141436-81273eff-a48a-4f58-8808-583c01ff8f42.png)
2. I have seen that this program supports localization now. But as a noob, I don't know how to do it at all. Could you please give me some more detailed guidance?

BTW, This program may be the best tool(with GUI) for extracting Umamusume sound resources at present. I hope to promote it to more local Umamusume players. Please keep developing.
Thanks.

**Comment by MarshmallowAndroid** [comment]
1. That's right. I fixed that horrible oversight in commit fe8f5599e5a70eefb001af99abf041ddeac62104. I'll publish a new release.

2. I'm on my way to update the README, but in advance I can say that you need Visual Studio to localize the text. I'll look into other methods in order to make it easier to localize the text, and at the same time still be able to use the Visual Studio designer.

Thank you for your kind words. I'll do my best.

**Comment by ChihyuenWang** [comment]
......and sorry, here comes the Question 3, it's a suggestion.
At present, if the user doesn't download the full game data, the missing part can still be displayed in the list, but the program will raise an error if I click it.
![Snipaste_2022-09-20_21-32-57](https://user-images.githubusercontent.com/12523783/191273468-f943fb4f-742a-4e2e-a198-ac5bfdf06897.png)
The game data is updated frequently. So, I suggest that the warning here can be more user-friendly. But my poor English cannot support me to give an example of how to be "user-friendly". I will wait for what you think about it. 🤔

**Comment by MarshmallowAndroid** [comment]
Actually, I'm pretty sure I check if the audio file exists (hence the loading) so this seems like a bug. I'll try to reproduce it and improve the message. Thank you for reporting. 😊

**Comment by MarshmallowAndroid** [comment]
Ah, it seems like it wasn't a bug, but an edge case. Uma Musume's audio middleware (CRIWARE) uses two files; the cue sheet file (ACB), and the bank file (AWB). All the sound data is in the bank file but the program still needs the cue sheet file for the track names.

In your case, you had the bank file but not the cue sheet file. I'll fix this in the next version.

**Comment by oBAMAEATSMYASS** [comment]
Very nice, response from developer. (*❦ω❦)*:･ﾟ✧*:･ﾟ✧

**Comment by ChihyuenWang** [comment]
The Release v1.2.2 seems to have fixed the various issues I raised. I appreciate your work.
