### ISSUE TITLE
Error after update a few days ago? 

### ISSUE THREAD

**Issue by 9oodra** [MarshmallowAndroid/UmaMusumeExplorer#4]
Always good to use. (Translator is in use)
After a new character came out a few days ago, only the newly released character can't extract the voice. Am I weird? I will attach a picture of the error.

![image](https://github.com/MarshmallowAndroid/UmaMusumeExplorer/assets/88673195/a82557cb-4d08-477b-bf8f-369859a32ddb)

이 대화 상자 대신 JIT(Just-in-time) 디버깅을 호출하는
방법에 대한 자세한 내용은 이 메시지의 뒷부분을 참조하십시오.

************** 예외 텍스트 **************
System.IO.InvalidDataException: Invalid HCA header.
   at ClHcaSharp.Header.DecodeHeader(HcaContext hca, Stream hcaStream)
   at ClHcaSharp.HcaDecoder..ctor(Stream hcaStream, UInt64 key)
   at UmaMusumeAudio.HcaWaveStream..ctor(Stream hcaFile, UInt64 key)
   at UmaMusumeAudio.UmaWaveStream..ctor(AwbReader awbReader, Int32 waveId)
   at UmaMusumeExplorer.Controls.LiveMusicPlayer.Classes.CharaTrack..ctor(AwbReader charaAwb, List`1 partTriggers, Int32 index) in C:\Users\Jacob\source\repos\UmaMusumeExplorer\UmaMusumeExplorer\Controls\LiveMusicPlayer\Classes\CharaTrack.cs:line 33
   at UmaMusumeExplorer.Controls.LiveMusicPlayer.Classes.SongMixer.InitializeCharaTracks(List`1 charaAwbs) in C:\Users\Jacob\source\repos\UmaMusumeExplorer\UmaMusumeExplorer\Controls\LiveMusicPlayer\Classes\SongMixer.cs:line 169
   at UmaMusumeExplorer.Controls.LiveMusicPlayer.PlayerForm.SetupUnit() in C:\Users\Jacob\source\repos\UmaMusumeExplorer\UmaMusumeExplorer\Controls\LiveMusicPlayer\PlayerForm.cs:line 297
   at UmaMusumeExplorer.Controls.LiveMusicPlayer.PlayerForm.LiveMusicPlayerForm_Load(Object sender, EventArgs e) in C:\Users\Jacob\source\repos\UmaMusumeExplorer\UmaMusumeExplorer\Controls\LiveMusicPlayer\PlayerForm.cs:line 64
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** 로드된 어셈블리 **************
System.Private.CoreLib
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Private.CoreLib.dll
----------------------------------------
UmaMusumeExplorer
    어셈블리 버전: 1.2.6.0
    Win32 버전: 해당 없음
    코드베이스: 
----------------------------------------
System.Runtime
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Runtime.dll
----------------------------------------
System.Windows.Forms.Primitives
    어셈블리 버전: 6.0.2.0
    Win32 버전: 6.0.1623.17402
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.16/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Windows.Forms
    어셈블리 버전: 6.0.2.0
    Win32 버전: 6.0.1623.17402
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.16/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.16/System.Drawing.Common.dll
----------------------------------------
System.Threading
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Collections.dll
----------------------------------------
Microsoft.Win32.Primitives
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Threading.Thread.dll
----------------------------------------
Accessibility
    어셈블리 버전: 4.0.0.0
    Win32 버전: 6.0.1623.17402
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.16/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.ComponentModel.TypeConverter.dll
----------------------------------------
UmaMusumeData
    어셈블리 버전: 1.0.0.0
    Win32 버전: 해당 없음
    코드베이스: 
----------------------------------------
Microsoft.Win32.SystemEvents
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.16/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.Concurrent
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Collections.Concurrent.dll
----------------------------------------
System.Numerics.Vectors
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Numerics.Vectors.dll
----------------------------------------
System.ComponentModel
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.ComponentModel.dll
----------------------------------------
System.Resources.Extensions
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.16/System.Resources.Extensions.dll
----------------------------------------
System.Memory
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Memory.dll
----------------------------------------
System.Drawing
    어셈블리 버전: 6.0.2.0
    Win32 버전: 6.0.1623.17402
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.16/System.Drawing.dll
----------------------------------------
System.ObjectModel
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.ObjectModel.dll
----------------------------------------
System.Linq
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Linq.dll
----------------------------------------
System.Private.Uri
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Private.Uri.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Runtime.Serialization.Formatters.dll
----------------------------------------
mscorlib
    어셈블리 버전: 4.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/mscorlib.dll
----------------------------------------
NAudio.WinMM
    어셈블리 버전: 2.1.0.0
    Win32 버전: 해당 없음
    코드베이스: 
----------------------------------------
netstandard
    어셈블리 버전: 2.1.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/netstandard.dll
----------------------------------------
NAudio.Core
    어셈블리 버전: 2.1.0.0
    Win32 버전: 해당 없음
    코드베이스: 
----------------------------------------
SQLite-net
    어셈블리 버전: 1.8.116.0
    Win32 버전: 해당 없음
    코드베이스: 
----------------------------------------
SQLitePCLRaw.batteries_v2
    어셈블리 버전: 2.0.4.976
    Win32 버전: 해당 없음
    코드베이스: 
----------------------------------------
SQLitePCLRaw.provider.dynamic_cdecl
    어셈블리 버전: 2.0.4.976
    Win32 버전: 해당 없음
    코드베이스: 
----------------------------------------
SQLitePCLRaw.core
    어셈블리 버전: 2.0.4.976
    Win32 버전: 해당 없음
    코드베이스: 
----------------------------------------
SQLitePCLRaw.nativelibrary
    어셈블리 버전: 2.0.4.976
    Win32 버전: 해당 없음
    코드베이스: 
----------------------------------------
System.Runtime.Loader
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    어셈블리 버전: 6.0.2.0
    Win32 버전: 6.0.1623.17402
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.16/ko/System.Windows.Forms.resources.dll
----------------------------------------
System.Xml.ReaderWriter
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Private.Xml.dll
----------------------------------------
System.Collections.NonGeneric
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Collections.NonGeneric.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
AssetStudio
    어셈블리 버전: 0.16.0.0
    Win32 버전: 해당 없음
    코드베이스: 
----------------------------------------
System.Threading.ThreadPool
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Threading.ThreadPool.dll
----------------------------------------
K4os.Compression.LZ4
    어셈블리 버전: 1.2.16.0
    Win32 버전: 해당 없음
    코드베이스: 
----------------------------------------
System.Text.RegularExpressions
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Text.RegularExpressions.dll
----------------------------------------
AssetStudioUtility
    어셈블리 버전: 0.16.0.0
    Win32 버전: 해당 없음
    코드베이스: 
----------------------------------------
SixLabors.ImageSharp
    어셈블리 버전: 1.0.0.0
    Win32 버전: 해당 없음
    코드베이스: 
----------------------------------------
Texture2DDecoderWrapper
    어셈블리 버전: 0.16.0.0
    Win32 버전: 해당 없음
    코드베이스: 
----------------------------------------
AssetStudio.PInvoke
    어셈블리 버전: 0.16.0.0
    Win32 버전: 해당 없음
    코드베이스: 
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Diagnostics.Process
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Diagnostics.Process.dll
----------------------------------------
System.Runtime.Extensions
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Runtime.Extensions.dll
----------------------------------------
System.Buffers
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Buffers.dll
----------------------------------------
CriWareFormats
    어셈블리 버전: 1.0.0.0
    Win32 버전: 해당 없음
    코드베이스: 
----------------------------------------
System.Diagnostics.StackTrace
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Collections.Immutable.dll
----------------------------------------
System.IO.Compression
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.IO.Compression.dll
----------------------------------------
System.Text.Encoding.Extensions
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Runtime.Intrinsics
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Runtime.Intrinsics.dll
----------------------------------------
UmaMusumeAudio
    어셈블리 버전: 1.0.0.0
    Win32 버전: 해당 없음
    코드베이스: 
----------------------------------------
ClHcaSharp
    어셈블리 버전: 1.0.0.0
    Win32 버전: 해당 없음
    코드베이스: 
----------------------------------------
System.IO.MemoryMappedFiles
    어셈블리 버전: 6.0.0.0
    Win32 버전: 6.0.1623.17311
    코드베이스: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.IO.MemoryMappedFiles.dll
----------------------------------------

************** JIT 디버깅 **************

**Comment by MarshmallowAndroid** [comment]
Sorry for the late reply, the problem was with my library. Issue should now be fixed.

**Comment by MarshmallowAndroid** [comment]
Added a new release with the issue fixed. Thank you for reporting.

**Comment by 9oodra** [comment]
thank you for solving it
