### ISSUE TITLE
New characters causing playback issues.

### ISSUE THREAD

**Issue by 9oodra** [MarshmallowAndroid/UmaMusumeExplorer#5]
Thank you always. Thanks to you, I am using the program well. It's nothing else, [Shinko Windy] character's [Make debut!] The character's voice is at double speed in the song's Live Music Player. is there a problem?

Also, if you export any song as a wav file after placing the character in the Live Music Player tab, the default setting is 4x sound amplification, but can't you export it at 1x or set it separately? 

I can be rude or clumsy using Google Translate. I'm sorry.

**Comment by MarshmallowAndroid** [comment]
Thank you for reporting issues, no worries about the Google Translate.

Confirmed Shinko Windy's voice plays at 2x speed only with Make debut!. I'll look into this with the audio decoder.

For the amplification issue, did you mean the Audio Player tab? When exporting to WAV, you can adjust the amplification before exporting and it will reflect in the output file. I hope this answers your question.

**Comment by 9oodra** [comment]
![114](https://github.com/MarshmallowAndroid/UmaMusumeExplorer/assets/88673195/68b79478-4d2f-439b-ba3f-875cad4ee52f)
If you export a song as a wav after setting up a character in the live music tab here, it seems that the sound comes out with 4x amplification set as default... Or maybe my ears are weird...

**Comment by 9oodra** [comment]
I compared it by amplifying it just in case, but the live music tab is a little big, but I think it's just a problem with my ears. thank you!!

**Comment by MarshmallowAndroid** [comment]
Ah, I see. My bad. Yes, the amplification in the audio player tab does not affect the live music player, but looking at the code, it seems that I have indeed amplified the volume in the live music player by 1.5x.

Thanks for the reports, both issues will be fixed in the next release.

**Comment by 9oodra** [comment]
Developer, the character Katsuragi Ace was updated today. If the character Katsuragi Ace is included in the member composition of the [Make debut!] song in the Live Music tab, the song does not play at around 2 minutes and 4 seconds, and it does not seem to be extracted. Can you please confirm? Or maybe it's my problem

**Comment by MarshmallowAndroid** [comment]
I'm updating the game to check this out, I'll report back with results afterwards.

**Comment by MarshmallowAndroid** [comment]
Confirmed broken. Will be updating the audio decoder to fix this issue.

**Comment by 9oodra** [comment]
Thank you for your hard work ^_^
