### ISSUE TITLE
[New Feature Request] Multi-WAV File Export Function

### ISSUE THREAD

**Issue by Maolaohei** [MarshmallowAndroid/UmaMusumeExplorer#6]
Hello, thank you very much for developing this software, but I would like to have a function to export multiple wav files (such as Shift+A select all and Ctrl+Left click), at this stage it is a bit cumbersome to export only a single one, I hope you can support it, thank you for your contribution.
I am using Deepl translation, please forgive me if the language is not fluent.

**Comment by MarshmallowAndroid** [comment]
Thank you for your feedback.  I will be working on it soon, but I honestly should have implemented this early on.

**Comment by MarshmallowAndroid** [comment]
Now implemented in commit 84b67a53562e30e0aa3c460090f79bf6dcaf79f1. Do check the generated build artifact in Actions if you want to try it out. Thank you.
