### ISSUE TITLE
I can't listen to the new live song released this time to commemorate the 2.5th anniversary due to an error.

### ISSUE THREAD

**Issue by 9oodra** [MarshmallowAndroid/UmaMusumeExplorer#7]
![image](https://github.com/MarshmallowAndroid/UmaMusumeExplorer/assets/88673195/f6d05684-a87b-4589-8850-eda2e41221d9)

error text

Just-In-Time (JIT) デバッグを呼び出すための詳細については、
ダイアログ ボックスではなく、このメッセージの最後を参照してください。

************** 例外テキスト **************
System.FormatException: The input string '' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Int32.Parse(String s)
   at UmaMusumeExplorer.Controls.LiveMusicPlayer.Classes.LyricsTrigger..ctor(String lyricsCsvLine) in D:\a\UmaMusumeExplorer\UmaMusumeExplorer\UmaMusumeExplorer\Controls\LiveMusicPlayer\Classes\LyricsTrigger.cs:line 15
   at UmaMusumeExplorer.Controls.LiveMusicPlayer.PlayerForm.LoadMusicScore() in D:\a\UmaMusumeExplorer\UmaMusumeExplorer\UmaMusumeExplorer\Controls\LiveMusicPlayer\PlayerForm.cs:line 336
   at UmaMusumeExplorer.Controls.LiveMusicPlayer.PlayerForm..ctor(LiveData live) in D:\a\UmaMusumeExplorer\UmaMusumeExplorer\UmaMusumeExplorer\Controls\LiveMusicPlayer\PlayerForm.cs:line 55
   at UmaMusumeExplorer.Controls.LiveMusicPlayer.LiveMusicPlayerControl.<.ctor>b__1_0(Object s, EventArgs e) in D:\a\UmaMusumeExplorer\UmaMusumeExplorer\UmaMusumeExplorer\Controls\LiveMusicPlayer\LiveMusicPlayerControl.cs:line 23
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** 読み込まれたアセンブリ **************
System.Private.CoreLib
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Private.CoreLib.dll
----------------------------------------
UmaMusumeExplorer
    アセンブリ バージョン:1.2.7.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Runtime
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31802
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.8/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31802
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.8/System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel.Primitives
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.8/System.Drawing.Common.dll
----------------------------------------
System.Threading
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Collections.dll
----------------------------------------
Microsoft.Win32.Primitives
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Threading.Thread.dll
----------------------------------------
Accessibility
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:7.0.823.31802
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.8/Accessibility.dll
----------------------------------------
System.Memory
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Memory.dll
----------------------------------------
System.Numerics.Vectors
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.8/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.NonGeneric
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Collections.NonGeneric.dll
----------------------------------------
UmaMusumeData
    アセンブリ バージョン:1.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
SQLite-net
    アセンブリ バージョン:1.8.116.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
netstandard
    アセンブリ バージョン:2.1.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/netstandard.dll
----------------------------------------
System.Linq
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Linq.dll
----------------------------------------
System.ComponentModel.TypeConverter
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ComponentModel
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.ComponentModel.dll
----------------------------------------
SQLitePCLRaw.core
    アセンブリ バージョン:2.0.4.976
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
SQLitePCLRaw.batteries_v2
    アセンブリ バージョン:2.0.4.976
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
SQLitePCLRaw.provider.dynamic_cdecl
    アセンブリ バージョン:2.0.4.976
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
SQLitePCLRaw.nativelibrary
    アセンブリ バージョン:2.0.4.976
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Linq.Expressions
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Linq.Expressions.dll
----------------------------------------
System.Collections.Concurrent
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Collections.Concurrent.dll
----------------------------------------
System.Private.Uri
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Private.Uri.dll
----------------------------------------
System.Resources.Extensions
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.8/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31802
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.8/System.Drawing.dll
----------------------------------------
System.ObjectModel
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.ObjectModel.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Runtime.Serialization.Formatters.dll
----------------------------------------
mscorlib
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/mscorlib.dll
----------------------------------------
NAudio.WinMM
    アセンブリ バージョン:2.1.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
NAudio.Core
    アセンブリ バージョン:2.1.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Xml.ReaderWriter
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Private.Xml.dll
----------------------------------------
AssetStudio
    アセンブリ バージョン:0.16.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
AssetStudioUtility
    アセンブリ バージョン:0.16.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
SixLabors.ImageSharp
    アセンブリ バージョン:1.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Text.RegularExpressions
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Text.RegularExpressions.dll
----------------------------------------
System.Threading.ThreadPool
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Threading.ThreadPool.dll
----------------------------------------
K4os.Compression.LZ4
    アセンブリ バージョン:1.2.16.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
Texture2DDecoderWrapper
    アセンブリ バージョン:0.16.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
AssetStudio.PInvoke
    アセンブリ バージョン:0.16.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Diagnostics.Process
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Diagnostics.Process.dll
----------------------------------------
System.Runtime.Extensions
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Runtime.Extensions.dll
----------------------------------------
System.Buffers
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Buffers.dll
----------------------------------------
System.Runtime.Intrinsics
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Runtime.Intrinsics.dll
----------------------------------------
System.Runtime.Loader
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31802
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.8/ja/System.Windows.Forms.resources.dll
----------------------------------------
System.Diagnostics.StackTrace
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Collections.Immutable.dll
----------------------------------------
System.IO.MemoryMappedFiles
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.IO.MemoryMappedFiles.dll
----------------------------------------
System.Text.Encoding.Extensions
    アセンブリ バージョン:7.0.0.0
    Win32 バージョン:7.0.823.31807
    コードベース:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.8/System.Text.Encoding.Extensions.dll
----------------------------------------

************** JIT デバッグ **************

I can't listen to the new live song released this time to commemorate the 2.5th anniversary due to an error. 
Can the developer please solve it??

**Comment by MarshmallowAndroid** [comment]
Thank you for your report. I have fixed this in the latest release.
